server:
  port: 8080
  context-path: /schoolportal
  tomcat:
    uri-encoding: UTF-8
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  application:
    name: schoolportal # 服务名称
  datasource:
    url: jdbc:mysql://localhost:3306/xjtmgcxy
    username: root
    password: root
mybatis:
  config-location:
    classpath: mybatis-config.xml